// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjx_DAZumOPVq3jUAhx6X0oUolf87Kz1s',
    appId: '1:533272709196:web:17689ed721840f356f0ce9',
    messagingSenderId: '533272709196',
    projectId: 'loocator-559f9',
    authDomain: 'loocator-559f9.firebaseapp.com',
    storageBucket: 'loocator-559f9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARNA7Rv_OUS9FS4z7-weKEaWOqSj0pHO0',
    appId: '1:533272709196:android:667988c415eea9766f0ce9',
    messagingSenderId: '533272709196',
    projectId: 'loocator-559f9',
    storageBucket: 'loocator-559f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4cjuBE65goysTRlirvDOoSXi5atvmlgc',
    appId: '1:533272709196:ios:ad4ccfaf3fd90c936f0ce9',
    messagingSenderId: '533272709196',
    projectId: 'loocator-559f9',
    storageBucket: 'loocator-559f9.firebasestorage.app',
    iosBundleId: 'com.example.loocator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4cjuBE65goysTRlirvDOoSXi5atvmlgc',
    appId: '1:533272709196:ios:ad4ccfaf3fd90c936f0ce9',
    messagingSenderId: '533272709196',
    projectId: 'loocator-559f9',
    storageBucket: 'loocator-559f9.firebasestorage.app',
    iosBundleId: 'com.example.loocator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjx_DAZumOPVq3jUAhx6X0oUolf87Kz1s',
    appId: '1:533272709196:web:c211f4a504aaccbc6f0ce9',
    messagingSenderId: '533272709196',
    projectId: 'loocator-559f9',
    authDomain: 'loocator-559f9.firebaseapp.com',
    storageBucket: 'loocator-559f9.firebasestorage.app',
  );
}
